# base level selection
TYPE_COURT = 1

# EconomicCourt branch
(EC_INSTANCE, EC_PROCEEDING, EC_OTHER, EC_CLAIM, EC_DUTY_PROPERTY, EC_DUTY_ORDER, EC_SUBJECT, EC_COURT_1, EC_COURT_2,
 EC_ADM_CASE, EC_DUTY_ADM_CASE, EC_DUTY_DOCUMENTS) = range(101, 113)
