version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - csd_bot:1.0
    command: python CalculatorOfTheStateDuty_BOT.py
    expose:
      - "6000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
